version: '3.8'

services:
  # FastAPI wrapper around vLLM
  model-api:
    build: .
    image: model-api-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    expose:
      - "8000"
    networks:
      - app-network

  # NGINX Load Balancer
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - model-api

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v2.53.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      - ./secrets:/etc/prometheus/secrets
    networks:
      - app-network
    depends_on:
      - model-api
    environment:
      - GRAFANA_PROMETHEUS_PASSWORD=${GRAFANA_PROMETHEUS_PASSWORD}
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo "$$GRAFANA_PROMETHEUS_PASSWORD" > /etc/prometheus/secrets/grafana-password &&
        chmod 600 /etc/prometheus/secrets/grafana-password &&
        exec /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --web.listen-address=:9090

volumes:
  prometheus_data:

networks:
  app-network:
    driver: bridge
